#include <stdio.h>
#include <string.h>

//to implement func 'my_strlen' which is 'strlen' alike. 
//Additionally, it cound handle strings without NUL-char in the end,  generated by using 'strn-' functions. 

unsigned int my_strlen(char string[], unsigned int array_space_len){
	unsigned int len;
	char *str_pt = string;

	for( len = 0; (*str_pt != '\0') && (len < array_space_len); len += 1, str_pt++ ){
		;
	}
	
	return len;
}


int main(void){
	char string_dst0[] = "1234567890";
	printf("%u\n", my_strlen(string_dst0, 11));

	char string_dst1[] = "1234567890";
	char string_src1[] = "12345";
	strncpy(string_dst1, string_src1, 8);
	printf("%u\n", my_strlen(string_dst1, 11));


	char string_dst2[] = "1234567890";
	char string_src2[] = "123456789000000";
	strncpy(string_dst2, string_src2, 11);	
	printf("%u\n", my_strlen(string_dst2, 11));
	
	return 0;
}
